version: '3.2'
# We need to use both file names to run:
#
#   docker-compose -f docker-compose-run-tests.yml up --exit-code-from cypress
#
services:
  cypress:
    #image: cypress-cucumber
    build:
      context: .
      dockerfile: Dockerfile
    command:
      ["cy:test"]
